# Generated by Django 3.0 on 2021-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20210315_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
    ]
