# Generated by Django 3.0 on 2021-03-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20210315_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha']},
        ),
    ]
